<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>PHP Example Challenge</title>
</head>
<body>
<h1>Top 25 Commits</h1>
<?php if (isset($commits) && ! empty($commits)) : ?>
    <table class="table">
        <thead>
            <tr>
                <td>Author</td>
                <td>Date Authored</td>
                <td>Committer</td>
                <td>Date Committed</td>
                <td>Hash</td>
            </tr>
        </thead>
        <tbody>
        <?php foreach($commits as $commit) { ?>
            <tr>
                <td><?=$commit->getAuthor()?></td>
                <td><?=$commit->getAuthoredDate()->format('Y-m-d H:i:s')?></td>
                <td><?=$commit->getCommitter()?></td>
                <td><?=$commit->getCommittedDate()->format('Y-m-d H:i:s')?></td>
                <td><?=$commit->getSha()?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>


<?php else: ?>
    <p>No commits were found</p>
<?php endif; ?>
</body>
</html>
